import Head from 'next/head';
import Header from '../Components/Header';
import Banner from '../Components/Banner';

export default function Home() {
  return (
    <div className="">

      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header />

    <Banner />

    </div>
  )
}
